envirment: dev
spring:
  datasource:
    url: jdbc:mysql://192.168.0.47:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Tdwl,123
    driver-class-name: com.mysql.jdbc.Driver
#    freemarker:
#      #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#      mode: HTML5
#      #编码 可不用配置
#      encoding: UTF-8
#      #内容类别,可不用配置
#      content-type: text/html
#      #开发配置为false,避免修改模板还要重启服务器
#      cache: false
#      #配置模板路径，默认是templates，可以不用配置
#      prefix: classpath:/templates

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
   root: debug
#server:
 # port: 8443
